apps/foundation/pages/index.tsx, libs/ui/src/components/FormItem/FormItem.stories.tsx, libs/ui/src/components/FormItem/FormItem.tsx, libs/ui/src/components/FormItem/index.tsx, libs/ui/src/components/Navigate/Navigate.stories.tsx, libs/ui/src/components/index.tsx
We need to investigate more about using react-hook-form in stories.
=> FormItem Component

libs/ui/src/admin/ArtApprovalModal/ArtApprovalModal.tsx, libs/ui/src/admin/ArtApprovalModal/ArtApprovalModel.stories.tsx, libs/ui/src/components/WImage/WImage.stories.tsx, libs/ui/src/components/WImage/WImage.tsx, package.json, yarn.lock
=> feat zoom property added to WImage

apps/admin/pages/_document.tsx, apps/admin/pages/accounts.tsx, apps/admin/pages/arts.tsx, apps/admin/pages/caps-maker.tsx, apps/admin/pages/competitions.tsx, apps/admin/pages/content-maker/human-rights.tsx, apps/admin/pages/content-maker/news.tsx, apps/admin/pages/hashtags/main.tsx, apps/admin/pages/hashtags/posts.tsx, apps/admin/pages/index.tsx, apps/admin/pages/translates/activities.tsx, apps/admin/pages/translates/announcements.tsx, apps/admin/pages/translates/arts.tsx, apps/admin/pages/translates/blogs.tsx, apps/admin/pages/translates/posts.tsx, libs/config/src/theme/admin.ts, libs/ui/src/admin/AdminNav/AdminNav.tsx, libs/ui/src/admin/AdminNav/AdminNavItem.tsx, libs/ui/src/admin/AdminNav/AdminNavItemCollapsed.tsx, libs/ui/src/admin/AdminNav/types.ts, libs/ui/src/admin/AdminSidebar/AdminSidebar.tsx, libs/ui/src/admin/AdminSidebar/AdminSidebarProfile.tsx, libs/ui/src/admin/Layout/AdminLayout.tsx, libs/ui/src/components/Navigate/Navigate.tsx
- Adds collapse/expand button at the bottom of the sidebar
- Changes default primary color as green
- Changes default font as Poppins
- Fixes loading indicator for ssg pages
=> Admin Collapsible Navbar

apps/samenvvv/pages/about-us.tsx
Note: Don't know which svg icons' colors should be changed. Rest is done, I think.
=> 241-samenvvv-about-us

apps/api/src/api/mention/controllers/custom.ts, apps/api/src/api/mention/routes/custom.ts, apps/api/src/api/mention/services/mention.ts
http://localhost:1337/api/mentions/search?q=samenvvv
=> backend mention search

apps/admin/pages/posts/index.tsx, libs/services/src/common/search.ts
=> Post filter by hashtag

libs/ui/src/admin/RecommendedTweetCard/RecommendedSocialButtons.tsx
create post from recommended tweet added
=> create post from recommended tweet

apps/admin/pages/translates/posts/[id].tsx, libs/config/src/data/routes.json, libs/config/src/menu/routes.ts, libs/config/src/menu/wsvvrijheid.ts, libs/ui/src/components/ArtModal/ArtModal.tsx, libs/ui/src/data/schemas/post.ts, libs/ui/src/data/schemas/translate.ts
platform muzic added and art station header menu fixed
=>  platform muzic and kunsthalte

libs/ui/src/academy/AcademyCard/AcademyCard.tsx, libs/ui/src/templates/PlatformTemplate/PlatformTemplate.tsx
- Add AcademyCards on the Wees Academy Page
- Add gradient shadow to the Text in de AcademyCard
=> add Cards to AcademyMainPage and refactor AcademyCard

libs/ui/src/components/PostMakerTweetCard/GridPostMakerTweetCard.stories.tsx, libs/ui/src/components/PostMakerTweetCard/GridPostMakerTweetCard.tsx, libs/ui/src/components/PostMakerTweetCard/PostMakerTweetCard.stories.tsx, libs/ui/src/components/PostMakerTweetCard/PostMakerTweetCard.tsx, libs/ui/src/components/PostMakerTweetCard/PostMakerTweetList.stories.tsx, libs/ui/src/components/PostMakerTweetCard/PostMakerTweetList.tsx
i need more info about functionalities of buttons
=> ui created

libs/context/package.json, libs/ui/src/post-maker/PostMaker.tsx, libs/ui/src/post-maker/TimelineTrendsTabs.tsx
=> timeline trends tab added

apps/foundation/components/HomePlatform/HomePlatform.tsx, packages/config/src/data/routes.json
=> music name updated

packages/ui/src/admin/CreateModelButton/CreateModelButton.tsx, packages/ui/src/admin/ModelForm/ModelCreateForm.tsx, packages/ui/src/admin/ModelForm/ModelCreateModal.tsx, packages/ui/src/admin/ModelForm/types.ts
=> draft recommendedtweet fixed

apps/dashboard/pages/api/kv/hashtag-sentences.ts, apps/samenvvv/pages/api/kv/hashtag-sentences.ts
I noticed that post maker page gives error while fetching hashtag sentences:
```json
{  "error": "Cannot read properties of undefined (reading 'length')" }
```
Hopefully it fixes the error
=> Allow reading hashtag sentences for public

apps/dashboard/pages/donations.tsx, packages/ui/src/components/MonthPicker/MonthPicker.tsx, packages/ui/src/components/MonthPicker/types.ts
I have added the MonthPicker component. I noticed also that clear button is not working yet on the MonthPicker component. Additionally, it seems that it needs to make some modifications to the filters by including '$lte' for it to work correctly.
=> MonthPicker is added

apps/api/src/api/profile/content-types/profile/schema.json, apps/api/types/generated/contentTypes.d.ts
This error was preventing the creation of a profile in the user register process.
=> avaliable hours default value changed from 0 to 1

.npmrc, apps/foundation/pages/courses/index.tsx, apps/samenvvv/pages/hashtags/[slug]/index.tsx, packages/services/src/hashtag/getBySlug.ts, packages/types/src/common.ts, packages/ui/src/components/AcademyCard/AcademyCard.tsx, packages/ui/src/components/PostImage/PostImage.tsx
@MustafaTRKYLMZ can you merge this?
=> Like-view blogs and arts

apps/foundation/pages/anbi.tsx
anbi page document Link updated
=> link updated

apps/dashboard/pages/[endpoint].tsx, apps/foundation/components/HomePlatform/HomePlatform.tsx, apps/foundation/pages/anbi.tsx, apps/kunsthalte/public/locales/nl/common.json, apps/samenvvv/public/locales/nl/common.json, packages/ui/src/components/PostSentenceCreator/PostSentenceCreator.tsx, packages/ui/src/components/PostSentenceCreator/index.ts, packages/ui/src/components/PostSentenceForm/PostSentenceForm.tsx, packages/ui/src/components/PostSentenceForm/types.ts, packages/ui/src/post-maker/PostMakerTweetCard/PostSentencesModal.tsx, packages/ui/src/post-maker/TweetGenAI/TweetGenAI.tsx
A new component "PostSentenceCreator" created
=> Add PostSentenceCreator component #1011

packages/ui/src/components/PostSentenceCreator/PostSentenceCreator.tsx, packages/ui/src/post-maker/TweetGenAI/TweetGenAI.tsx
Remove AI-generated posts from the stack once they are added to the sentences section
=> Remove saved AI-generated posts from the list

apps/dashboard/public/locales/en/common.json, apps/foundation/public/locales/en/common.json, apps/kunsthalte/public/locales/en/common.json, apps/lotus/public/locales/en/common.json, apps/samenvvv/public/locales/en/common.json, packages/ui/public/locales/en/common.json, packages/ui/src/components/PostSentenceCreator/PostSentenceCreator.tsx
- Prevent users from adding existing AI-generated posts to the "Sentences" section
- Provide users with feedback when:
- A post is successfully added to the "Sentences" section
- An attempt is made to add a duplicate post to the "Sentences" section
=> Enhance Sentence Creation

apps/api/types/generated/contentTypes.d.ts, apps/dashboard/pages/archive-content/[id].tsx
- Enables i18n for ArchiveContent model
- Adds Tabs in ArchiveContent detail page
=> Update content archive page

apps/dashboard/pages/courses/index.tsx
https://github.com/freedomcombination/monorepo/issues/880
=> list draft courses

packages/ui/src/components/JoinForm/JoinForm.tsx
https://github.com/freedomcombination/monorepo/issues/945
by the way, i couldnt reproduce same warning at issue. but translation is okey now.
=> application form translate

apps/api/src/api/blog/controllers/blog.ts, apps/api/src/api/blog/controllers/custom.ts, apps/api/src/api/blog/routes/custom.ts, apps/api/src/utils/checkRecaptcha.ts, apps/foundation/pages/blog/[slug].tsx, apps/foundation/pages/blog/index.tsx, packages/secrets/src/index.ts, packages/services/src/blog/get.ts, packages/services/src/blog/getBlogBySlug.ts, packages/services/src/blog/like.ts, packages/types/src/blog.ts, packages/ui/src/components/BlogCard/BlogCard.tsx, packages/ui/src/components/BlogDetail/BlogDetail.tsx
- added an if for development recaptcha()
- blog find() function now checks user is in likers list.and add isLiked value and save same bandwidth (likers is cutted out) and likes count is calculated here.
- like and unlike functions has changed a little bit. there is a comment.
- added user token to every blog releated strapiRequest
- and chanced icon color a little. more colorblind friendly :D i couldnt tell if i liked or not.
=> backend isLiked

apps/foundation/pages/club/index.tsx, apps/kunsthalte/pages/club/arts/index.tsx, packages/services/src/art/getByCategories.ts, packages/services/src/art/getBySlug.ts, packages/services/src/art/getClubQueryClient.ts, packages/services/src/art/index.ts, packages/services/src/art/like.ts, packages/ui/src/components/ArtCard/ArtCard.tsx, packages/ui/src/components/ArtCard/ArtCardBase.tsx, packages/ui/src/components/ArtDetail/ArtDetail.tsx, packages/ui/src/templates/ArtClubTemplate/ArtClubTemplate.tsx
=> Art query fixes

apps/trend-rights/components/Layout/Layout.tsx, apps/trend-rights/components/PlusButton/PlusButton.tsx, apps/trend-rights/pages/hashtags/[slug]/index.tsx, packages/ui/src/Providers.tsx
Timeline and Trends buttons are not included.
=> Hashtag Plus Button

apps/dashboard/pages/courses/[id].tsx, apps/trend-rights/components/Layout/Layout.tsx, packages/config/src/data/routes.ts, packages/config/src/menu/routes.ts, packages/config/src/menu/trend-rights.ts, packages/ui/src/post-maker/GenAI/ArchivePopover.tsx
https://github.com/freedomcombination/monorepo/issues/951
=> Burak-trend-menus

apps/api/src/api/hashtag/content-types/hashtag/lifecycles.ts, apps/dashboard/pages/courses/[id].tsx, apps/trend-rights/middleware.ts, package.json, packages/ui/src/post-maker/GenAI/ArchivePopover.tsx, turbo.json, yarn.lock
https://github.com/freedomcombination/monorepo/issues/1155
=> Burak-last-hashtag-redirect

apps/trend-rights/pages/api/auth/logout.ts, packages/ui/src/components/Header/ProfileMenu.tsx
https://github.com/freedomcombination/monorepo/issues/1199
and added loading spinner to login button
=> trend-right logout

packages/ui/src/components/Header/ProfileMenu.tsx
https://github.com/freedomcombination/monorepo/issues/1217
=> Burak-fix-returnurl

packages/services/src/api/og.tsx, packages/ui/src/components/Caps/Caps.tsx
https://github.com/freedomcombination/monorepo/issues/737
=> Burak-caps-text

apps/api/src/api/hashtag/content-types/hashtag/lifecycles.ts, apps/trend-rights/middleware.ts, packages/ui/src/Providers.tsx, packages/ui/src/components/Header/Header.tsx
Could you look into this? I left some comments in the code
=> Fix edge config

apps/api/src/api/profile/controllers/profile.ts, apps/api/src/utils/getProfile.ts, packages/ui/src/data/requestArgs/index.ts
https://github.com/freedomcombination/monorepo/issues/1226
=> filtered profiles endpoint for PlatformCoordinator role

apps/dashboard/pages/[endpoint].tsx, packages/ui/src/admin/ModelForm/ModelDynamicSelect.tsx, packages/ui/src/admin/ModelStatusFilters/ModelStatusFilters.tsx, packages/ui/src/data/requestArgs/index.ts
For profiles page
Platform and profileStatus filter added
=> platform and profilestatus added

packages/ui/src/post-maker/PostMakerTweetCard/PostMakerTweetList.tsx
https://github.com/freedomcombination/monorepo/issues/1295
=> Burak-postmaker-list-order

apps/api/src/api/user-feedback/controllers/user-feedback.ts, packages/services/src/userFeedback/userFeedback.ts, packages/ui/src/components/UserFeedbackForm/UserFeedbackForm.tsx
https://github.com/freedomcombination/monorepo/issues/1166
can you check in your system please, because recaptcha allways (in everywhere) returns my request.
=> Burak-feedback

apps/dashboard/app/api/gen-archive-content-posts/route.ts, apps/dashboard/app/api/route-tweet-gen/route.ts
• Upgraded the AI model from `gpt-4` to `gpt-4o` as a result of an investigation suggested in issue #1294.
=> Switching from gpt-4 to gpt-4o

apps/api/src/api/profile/controllers/profile.ts
im not sure if we check name in query
` $and: [{ email: { $eq: email } }, { **name: { $eq: name }** }],`
=> update profile if already exist

apps/api/src/api/blog/controllers/blog.ts, apps/api/src/api/blog/routes/custom.ts, apps/api/types/generated/contentTypes.d.ts, packages/lib/src/request/request.ts
@ertugrul-aydin Can you do some tests if this works
=> Refactor blog findOne controller

packages/ui/src/components/CollectionList/CollectionList.tsx
collection list fixed
div removed, stack added. Now It must be vertical.
=> collection list fixed

apps/dashboard/pages/courses/[id].tsx
https://github.com/freedomcombination/monorepo/issues/1256
=> course filter fixed.

apps/api/types/generated/components.d.ts, apps/dashboard/pages/assets/index.tsx, apps/dashboard/public/locales/en/common.json, apps/dashboard/public/locales/nl/common.json, apps/dashboard/public/locales/tr/common.json, apps/foundation/public/locales/en/common.json, apps/foundation/public/locales/nl/common.json, apps/foundation/public/locales/tr/common.json, apps/kunsthalte/public/locales/en/common.json, apps/kunsthalte/public/locales/nl/common.json, apps/kunsthalte/public/locales/tr/common.json, apps/lotus/public/locales/en/common.json, apps/lotus/public/locales/nl/common.json, apps/lotus/public/locales/tr/common.json, apps/trend-rights/public/locales/en/common.json, apps/trend-rights/public/locales/nl/common.json, apps/trend-rights/public/locales/tr/common.json, packages/ui/public/locales/en/common.json, packages/ui/public/locales/nl/common.json, packages/ui/public/locales/tr/common.json, packages/ui/src/components/DataTables/DataTable.tsx, packages/ui/src/components/DataTables/types.ts, packages/ui/src/hooks/tables/assets.tsx
=> added total price to asset

packages/utils/courseLogic.ts
it seems somehow both comes undefined and find return a profile.
=> fixed false already registered notification.
